import time

print("|       |", end='\r')
time.sleep(1)
print("|=      |", end='\r')
time.sleep(1)
print("|==     |", end='\r')
time.sleep(1)
print("|===    |", end='\r')
time.sleep(1)
print("|====   |", end='\r')
time.sleep(1)
print("|=====  |", end='\r')
time.sleep(1)
print("|====== |", end='\r')
time.sleep(1)
print("|=======|", end=' ')
time.sleep(1)
print("DONE", end=' ')